### ISSUE TITLE
Nightmare: «Evaluation timed out after 30000msec»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [dmitry-ai/airbnb-parser#1]
> (node:3620) UnhandledPromiseRejectionWarning: Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
    at Timeout._onTimeout (C:\work\clients\nightmare\code\node_modules\nightmare\lib\actions.js:634:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:3620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by dmitrii-fediuk** [comment]
Fixed.
